<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import ClerkProviderWithKey from "../components/ClerkProviderWithKey";
import 'bootstrap/dist/css/bootstrap.min.css';
import './custom.css';

export const metadata = {
  title: 'WaveOver',
  description: 'Talk It Out — Without Talking Over Each Other',
>>>>>>> vercel-deployment
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
=======
      <body>
        <ClerkProviderWithKey>
          {children}
        </ClerkProviderWithKey>
      </body>
    </html>
  );
} 
>>>>>>> vercel-deployment
