name: Build and Deploy Backend

on:
  push:
    paths:
      - 'server/**'
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: WaveOver-Development
    env:
      AWS_DEFAULT_REGION: eu-west-1 
    permissions:
      id-token: write
      contents: read


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264329805:role/GitHubActionsRole-Dev
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF_NAME | tr / -)-$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -f server/WaveOverBackDocker -t 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG client/
          docker tag 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:latest
      

      # Step 7: Push the Docker Image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker push 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG
          docker push 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:latest

