name: Build and Deploy to EC2

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/deploy-front.yml'
    branches:
      - feedback-form  # Trigger the workflow when commits are pushed to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: WaveOver-Development
    env:
      AWS_DEFAULT_REGION: eu-west-1
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Fetching OIDC Token..."
          TOKEN=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')
          echo "OIDC Token (encoded): $TOKEN"
          echo "OIDC Token (decoded):"
          echo "$TOKEN" | base64 -d | jq '.'
      
      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264329805:role/GitHubActionsRole-Dev
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      # New Step: Update SSM Parameter with commit hash
      - name: Update SSM Parameter with commit hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          aws ssm put-parameter \
            --name "frontend-waveover-development-ecr-commit-hash-tag" \
            --value "$COMMIT_HASH" \
            --type "String" \
            --overwrite

      # Step 5: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: waveover-development
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF_NAME | tr / -)-$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
          echo "Building Docker Image..."
          docker build -f client/WaveOverFrontDocker -t $REGISTRY/$REPOSITORY:$IMAGE_TAG client/
      
          echo "Tagging Image with commit hash and latest..."
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:$COMMIT_HASH
          docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$REPOSITORY:latest
      
          echo "Pushing all image tags to ECR..."
          docker push --all-tags $REGISTRY/$REPOSITORY

      # Step 8: Start EC2 Instance
      - name: Start EC2 Instance
        run: |
          echo "DEV_FRONTEND_INSTANCE_ID: ${{ secrets.DEV_FRONTEND_INSTANCE_ID }}"
          aws ec2 start-instances --instance-ids ${{ secrets.DEV_FRONTEND_INSTANCE_ID}} --region ${{ env.AWS_DEFAULT_REGION }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.DEV_FRONTEND_INSTANCE_ID}} --region ${{ env.AWS_DEFAULT_REGION }}

      # Configure CloudWatch agent using SSM
      - name: Configure CloudWatch Agent
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Configure CloudWatch agent" \
            --parameters commands='[
              "echo \"Downloading CloudWatch agent configuration from S3...\"",
              "sudo aws s3 cp s3://waveover-development-config/Frontend/Cloudwatch-agent/cloudwatch-agent-frontend-config.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json",
              "echo \"Configuring CloudWatch agent...\"",
              "sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json",
              "echo \"Starting CloudWatch agent...\"",
              "sudo systemctl start amazon-cloudwatch-agent",
              "echo \"Verifying CloudWatch agent status...\"",
              "sudo systemctl status amazon-cloudwatch-agent"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}

      # Clean up Docker on EC2 using SSM
      - name: Clean up Docker on EC2
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Clean up Docker containers and images" \
            --parameters commands='[
              "REPOSITORY=\"waveover-development\"",
              "AWS_REGION=\"eu-west-1\"",
              "REGISTRY=\"058264329805.dkr.ecr.$AWS_REGION.amazonaws.com\"",
              "echo \"Stopping and removing the old container (if exists)...\"",
              "docker stop waveover-container || true",
              "docker rm waveover-container || true",
              "echo \"Fetching latest image ID from ECR...\"",
              "LATEST_IMAGE_ID=$(docker images --format \"{{.ID}}\" $REGISTRY/$REPOSITORY:latest)",
              "echo \"Finding all old images except the latest...\"",
              "docker images $REGISTRY/$REPOSITORY --format \"{{.ID}} {{.Repository}}:{{.Tag}}\" | grep -v $LATEST_IMAGE_ID | awk \"{print $1}\" | xargs -r docker rmi -f",
              "echo \"Pruning unused resources...\"",
              "docker system prune -f"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}

      # Deploy to EC2 using SSM
      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker container for frontend" \
            --parameters commands='[
              "REPOSITORY=\"waveover-development\"",
              "AWS_REGION=\"eu-west-1\"",
              "REGISTRY=\"058264329805.dkr.ecr.$AWS_REGION.amazonaws.com\"",
              "echo \"Logging in to Amazon ECR...\"",
              "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REGISTRY",
              "echo \"Pulling latest image...\"",
              "docker pull $REGISTRY/$REPOSITORY:latest",
              "echo \"Running container...\"",
              "docker run -d --name waveover-container -p 80:80 $REGISTRY/$REPOSITORY:latest"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}

      # Step 10: Output Docker Image Details
      - name: Output Docker Image Details
        env:
              REPOSITORY: waveover-development
        run: |
          echo "Docker image built and used:"
          echo "Repository: 058264329805.dkr.ecr.eu-west-1.amazonaws.com/$REPOSITORY"
          echo "Tag: $COMMIT_HASH"
          echo "Latest Tag: latest"







