name: Build and Deploy to EC2

on:
  push:
    branches:
      - master  # Trigger the workflow when commits are pushed to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-west-1

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1  


      # Step 3: Build and Tag the Docker Image
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF_NAME | tr / -)-$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:$IMAGE_TAG .
          docker tag 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:$IMAGE_TAG 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:latest

      # Step 4: Push the Docker Image to Amazon ECR
      - name: Push Docker image to ECR
        run: |
          docker push 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:$IMAGE_TAG
          docker push 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:latest

      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.INSTANCE_ID }} --region ${{ env.AWS_REGION }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.INSTANCE_ID }} --region ${{ env.AWS_REGION }}

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEV_HOST_IP}}
          username: ubuntu
          key: ${{ secrets.WAVEOVER_DEV_PEM_KEY}}
          port: 22
          script: |
            docker pull 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:latest
            docker stop waveover-container || true
            docker rm waveover-container || true
            docker run -d --name waveover-container -p 3000:3000 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development:latest

