name: Build and Deploy Backend

on:
  push:
    paths:
      - 'server/**'
      - '!server/lambdas/**'
      - '!server/scripts/**'
      - '.github/workflows/deploy-back.yml'
    branches:
      - feedback-form

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: WaveOver-Development
    env:
      AWS_DEFAULT_REGION: eu-west-1
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug OIDC Token
        run: |
          echo "Fetching OIDC Token..."
          TOKEN=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL | jq -r '.value')
          echo "OIDC Token (encoded): $TOKEN"
          echo "OIDC Token (decoded):"
          echo "$TOKEN" | base64 -d | jq '.'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::058264329805:role/GitHubActionsRole-Dev
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Update SSM Parameter with commit hash
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          aws ssm put-parameter \
            --name "waveover-development-backend-ecr-commit-hash-tag" \
            --value "$COMMIT_HASH" \
            --type "String" \
            --overwrite

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF_NAME | tr / -)-$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
          docker build -f server/WaveOverBackDocker -t 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG server/
          
          # Tag with commit hash and latest
          docker tag 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$COMMIT_HASH
          docker tag 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:$IMAGE_TAG 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:latest

      - name: Push Docker image to ECR
        run: |
          docker push --all-tags 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend
      
      - name: Start EC2 Instance
        run: |
          echo "DEV_BACKEND_INSTANCE_ID: ${{ secrets.DEV_BACKEND_INSTANCE_ID }}"
          aws ec2 start-instances --instance-ids ${{ secrets.DEV_BACKEND_INSTANCE_ID }} --region ${{ env.AWS_DEFAULT_REGION }}
          aws ec2 wait instance-running --instance-ids ${{ secrets.DEV_BACKEND_INSTANCE_ID }} --region ${{ env.AWS_DEFAULT_REGION }}

      # Configure CloudWatch agent
      - name: Configure CloudWatch Agent
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Configure CloudWatch agent" \
            --parameters commands='[
              "echo \"Downloading CloudWatch agent configuration from S3...\"",
              "sudo aws s3 cp s3://waveover-development-config/Backend/Cloudwatch-agent/cloudwatch-agent-backend-config.json /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json",
              "echo \"Configuring CloudWatch agent...\"",
              "sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json",
              "echo \"Starting CloudWatch agent...\"",
              "sudo systemctl start amazon-cloudwatch-agent",
              "echo \"Verifying CloudWatch agent status...\"",
              "sudo systemctl status amazon-cloudwatch-agent"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}

      - name: Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy Docker container for backend" \
            --parameters commands='[
              "aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 058264329805.dkr.ecr.eu-west-1.amazonaws.com",
              "docker pull 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:latest",
              "docker run -d --name waveover-backend-container -p 5000:5000 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend:latest"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}
      
      - name: Clean up Docker on EC2
        run: |
          # Convert the script content to base64 to handle special characters safely
          SCRIPT_CONTENT=$(base64 -w 0 server/server-cleanup.sh)
          
          aws ssm send-command \
            --instance-ids ${{ secrets.DEV_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Upload and execute cleanup script" \
            --parameters commands='[
              "echo \"'$SCRIPT_CONTENT'\" | base64 -d > /tmp/server-cleanup.sh",
              "chmod +x /tmp/server-cleanup.sh",
              "/tmp/server-cleanup.sh"
            ]' \
            --region ${{ env.AWS_DEFAULT_REGION }}
  
      - name: Output Docker Image Details
        run: |
          echo "Docker image built and used:"
          echo "Repository: 058264329805.dkr.ecr.eu-west-1.amazonaws.com/waveover-development-backend"
          echo "Tag: $IMAGE_TAG"
          echo "Latest Tag: latest"

